In [ ]:
import pandas as pd

battery = pd.read_csv("battery_sensor_readings.csv")
trackers = pd.read_csv("trackers_metadata.csv")
market = pd.read_csv("market_prices.csv")

battery.head()

,tracker_id,timestamp,battery_voltage,current,temperature,state_of_charge
0,T020,2026-08-13 12:45:00,24.86,3.63,28.5,100.0
1,T013,2026-08-28 16:30:00,24.81,1.88,27.7,100.0
2,T014,2026-08-09 05:15:00,24.27,-0.88,21.5,80.3
3,T016,2026-08-27 05:30:00,24.47,-0.61,22.9,88.2
4,T008,2026-08-30 19:00:00,24.90,1.32,23.6,100.0

In [10]:
trackers.head()

  tracker_id   latitude  longitude install_date
0       T001  37.951262  -8.888100   2024-03-19
1       T002  37.948367  -8.883302   2024-03-02
2       T003  37.952696  -8.885625   2024-04-13
3       T004  37.951414  -8.884468   2024-05-02
4       T005  37.950215  -8.887600   2024-08-24

In [11]:
market.head

<bound method NDFrame.head of                timestamp  market_price
0    2026-08-01 00:00:00         26.93
1    2026-08-01 01:00:00         37.22
2    2026-08-01 02:00:00         31.32
3    2026-08-01 03:00:00         33.35
4    2026-08-01 04:00:00         27.53
..                   ...           ...
715  2026-08-30 19:00:00         66.38
716  2026-08-30 20:00:00         69.58
717  2026-08-30 21:00:00         60.86
718  2026-08-30 22:00:00         52.45
719  2026-08-30 23:00:00         49.38

[720 rows x 2 columns]>